CC = gfortran
# Librairies utilisees
LIBS = 
# Options de compilation
FFLAGS = 
# dossier pour les fichiers binaires
BIN = bin/
# dossier pour les codes du modele 1D
FILE_1D = 1D/
# dossier pour les codes du modele 2D
FILE_2D = 2D/

trafic_scalaire: 


trafic_system:



